# SPDX-FileCopyrightText: 2026 Institute of Radiation Physics, Helmholtz-Zentrum Dresden-Rossendorf
#
# SPDX-License-Identifier: MIT

"""Unit tests for the analysis engine (:mod:`pic_agentic.analysis`)."""

from __future__ import annotations

import json

from pic_agentic import analysis

SECRET = "super-secret-token-value"


def _setup(tmp_path):
    setup = tmp_path / "input"
    (setup / "metadata").mkdir(parents=True)
    (setup / "ro-crate-metadata.json").write_text(
        json.dumps(
            {
                "@graph": [
                    {
                        "@id": "./",
                        "name": "PIConGPU simulation autogenerated",
                        "datePublished": "2026-09-26T10:00:00+00:00",
                        "mainEntity": {"@id": "workflow/workflow.cwl"},
                        "instrument": {"@id": "#picongpu", "name": "PIConGPU"},
                    },
                    {"@id": "workflow/workflow.cwl", "@type": "ComputationalWorkflow"},
                ],
            },
        ),
        encoding="utf-8",
    )
    (setup / "metadata" / "pypicongpu_runner.json").write_text(
        json.dumps({"run_dir": "/x/run", "setup_dir": "/x/input", "token": SECRET}),
        encoding="utf-8",
    )
    (setup / "metadata" / "rc_params.json").write_text(
        json.dumps({"build_jobs": 4, "api_key": SECRET}),
        encoding="utf-8",
    )
    (setup / "metadata" / "pypicongpu_rendering_context.json").write_text(
        json.dumps({"grid": "3d"}),
        encoding="utf-8",
    )
    return setup


def test_read_rocrate_extracts_fields(tmp_path) -> None:
    rocrate = analysis.read_rocrate(_setup(tmp_path))
    assert rocrate["name"] == "PIConGPU simulation autogenerated"
    assert rocrate["mainEntity"] == {"@id": "workflow/workflow.cwl"}
    assert rocrate["software"] == {"name": "PIConGPU", "id": "#picongpu"}


def test_read_rocrate_missing_is_empty(tmp_path) -> None:
    assert analysis.read_rocrate(tmp_path / "nope") == {}


def test_read_metadata_redacts_secrets(tmp_path) -> None:
    metadata = analysis.read_pypicongpu_metadata(_setup(tmp_path))
    assert metadata["runner"]["run_dir"] == "/x/run"
    assert "token" not in metadata["runner"]
    assert "api_key" not in metadata["rc_params"]
    assert metadata["rendering_context"] == {"grid": "3d"}
    # The secret must not appear anywhere in the serialised result.
    assert SECRET not in json.dumps(metadata)


def test_read_metadata_missing_is_empty(tmp_path) -> None:
    metadata = analysis.read_pypicongpu_metadata(tmp_path / "nope")
    assert metadata == {"runner": {}, "rc_params": {}, "rendering_context": {}}


def test_read_openpmd_summary_from_files(tmp_path) -> None:
    output = tmp_path / "run" / "simOutput"
    (output / "openPMD").mkdir(parents=True)
    (output / "openPMD" / "sim_0000.bp").write_bytes(b"\x00\x01")
    (output / "energy.txt").write_text("a\nb\n", encoding="utf-8")
    summary = analysis.read_openpmd_summary(output)
    assert "latest_step" in summary
    assert isinstance(summary.get("iterations"), list)


def test_read_openpmd_summary_missing_is_empty(tmp_path) -> None:
    assert analysis.read_openpmd_summary(tmp_path / "nope") == {}


def test_synthesize_answer_default_lists_facts(tmp_path) -> None:
    setup = _setup(tmp_path)
    answer = analysis.analyze(tmp_path / "run", setup, None)["answer"]
    assert "PIConGPU simulation autogenerated" in answer


def test_synthesize_answer_filters_by_query() -> None:
    rocrate = {"name": "Laser sweep", "software": {"name": "PIConGPU", "id": "#p"}}
    openpmd = {"iterations": [0, 10], "latest_step": 10, "backends": ["openpmd-adios2"]}
    answer = analysis.synthesize_answer("iterations", rocrate, {}, openpmd)
    assert "Matched the query" in answer
    assert "openPMD iterations" in answer
    assert "Laser sweep" not in answer


def test_synthesize_answer_no_match_reports_and_falls_back() -> None:
    answer = analysis.synthesize_answer("zzz-nonexistent", {"name": "x"}, {}, {})
    assert "No analysis fields matched" in answer


def test_analyze_never_raises_on_garbage(tmp_path) -> None:
    bad = tmp_path / "input"
    bad.mkdir()
    (bad / "ro-crate-metadata.json").write_text("{not json", encoding="utf-8")
    (bad / "metadata").mkdir()
    (bad / "metadata" / "rc_params.json").write_text("[1,2,3]", encoding="utf-8")
    sections = analysis.analyze(tmp_path / "run", bad, tmp_path / "missing")
    assert set(sections) == {"rocrate", "metadata", "openpmd", "answer"}
    assert sections["rocrate"] == {}
    assert isinstance(sections["answer"], str)


def test_analyze_derives_setup_from_run_dir(tmp_path) -> None:
    setup = _setup(tmp_path)
    (setup.parent / "run").mkdir()
    sections = analysis.analyze(tmp_path / "run", None, None)
    assert sections["rocrate"]["name"]


def test_analyze_with_no_paths_is_empty_but_valid() -> None:
    sections = analysis.analyze(None, None, None)
    assert sections["rocrate"] == {}
    assert "No analysis metadata" in sections["answer"]


def test_analyze_rejects_symlinked_setup_escape(tmp_path) -> None:
    """A symlinked ``input`` must not let analysis read outside the run base."""
    base = tmp_path / "base"
    (base / "run").mkdir(parents=True)
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "ro-crate-metadata.json").write_text(
        '{"@graph": [{"@id": "./", "name": "SECRET CRATE"}]}',
        encoding="utf-8",
    )
    (base / "input").symlink_to(outside)
    sections = analysis.analyze(base / "run", None, None)
    assert sections["rocrate"] == {}


def test_readers_never_raise_on_bad_bytes(tmp_path) -> None:
    setup = tmp_path / "input"
    (setup / "metadata").mkdir(parents=True)
    (setup / "ro-crate-metadata.json").write_bytes(b"\xff\xfe not utf-8")
    (setup / "metadata" / "rc_params.json").write_bytes(b"\x00null byte")
    assert analysis.read_rocrate(setup) == {}
    assert analysis.read_pypicongpu_metadata(setup)["rc_params"] == {}
    # A null byte in the path itself must not raise either.
    assert analysis.read_rocrate("bad\x00path") == {}
