# SPDX-FileCopyrightText: 2026 Institute of Radiation Physics, Helmholtz-Zentrum Dresden-Rossendorf
#
# SPDX-License-Identifier: MIT

"""Unit tests for the analysis engine (:mod:`pic_agentic.analysis`)."""

from __future__ import annotations

import json

import pytest

from pic_agentic import analysis

SECRET = "super-secret-token-value"


def _setup(tmp_path):
    setup = tmp_path / "input"
    (setup / "metadata").mkdir(parents=True)
    (setup / "ro-crate-metadata.json").write_text(
        json.dumps(
            {
                "@graph": [
                    {
                        "@id": "./",
                        "name": "PIConGPU simulation autogenerated",
                        "datePublished": "2026-09-26T10:00:00+00:00",
                        "mainEntity": {"@id": "workflow/workflow.cwl"},
                        "instrument": {"@id": "#picongpu", "name": "PIConGPU"},
                    },
                    {"@id": "workflow/workflow.cwl", "@type": "ComputationalWorkflow"},
                ],
            },
        ),
        encoding="utf-8",
    )
    (setup / "metadata" / "pypicongpu_runner.json").write_text(
        json.dumps({"run_dir": "/x/run", "setup_dir": "/x/input", "token": SECRET}),
        encoding="utf-8",
    )
    (setup / "metadata" / "rc_params.json").write_text(
        json.dumps({"build_jobs": 4, "api_key": SECRET}),
        encoding="utf-8",
    )
    (setup / "metadata" / "pypicongpu_rendering_context.json").write_text(
        json.dumps({"grid": "3d"}),
        encoding="utf-8",
    )
    return setup


def test_read_rocrate_extracts_fields(tmp_path) -> None:
    rocrate = analysis.read_rocrate(_setup(tmp_path))
    assert rocrate["name"] == "PIConGPU simulation autogenerated"
    assert rocrate["mainEntity"] == {"@id": "workflow/workflow.cwl"}
    assert rocrate["software"] == {"name": "PIConGPU", "id": "#picongpu"}


def test_read_rocrate_missing_is_empty(tmp_path) -> None:
    assert analysis.read_rocrate(tmp_path / "nope") == {}


def test_read_metadata_redacts_secrets(tmp_path) -> None:
    metadata = analysis.read_pypicongpu_metadata(_setup(tmp_path))
    assert metadata["runner"]["run_dir"] == "/x/run"
    assert "token" not in metadata["runner"]
    assert "api_key" not in metadata["rc_params"]
    assert metadata["rendering_context"] == {"grid": "3d"}
    # The secret must not appear anywhere in the serialised result.
    assert SECRET not in json.dumps(metadata)


def test_read_metadata_missing_is_empty(tmp_path) -> None:
    metadata = analysis.read_pypicongpu_metadata(tmp_path / "nope")
    assert metadata == {"runner": {}, "rc_params": {}, "rendering_context": {}}


def test_read_openpmd_summary_from_files(tmp_path) -> None:
    output = tmp_path / "run" / "simOutput"
    (output / "openPMD").mkdir(parents=True)
    (output / "openPMD" / "sim_0000.bp").write_bytes(b"\x00\x01")
    (output / "energy.txt").write_text("a\nb\n", encoding="utf-8")
    summary = analysis.read_openpmd_summary(output)
    assert "latest_step" in summary
    assert isinstance(summary.get("iterations"), list)


def test_read_openpmd_summary_missing_is_empty(tmp_path) -> None:
    assert analysis.read_openpmd_summary(tmp_path / "nope") == {}


def test_synthesize_answer_default_lists_facts(tmp_path) -> None:
    setup = _setup(tmp_path)
    answer = analysis.analyze(tmp_path / "run", setup, None)["answer"]
    assert "PIConGPU simulation autogenerated" in answer


def test_synthesize_answer_filters_by_query() -> None:
    rocrate = {"name": "Laser sweep", "software": {"name": "PIConGPU", "id": "#p"}}
    openpmd = {"iterations": [0, 10], "latest_step": 10, "backends": ["openpmd-adios2"]}
    answer = analysis.synthesize_answer("iterations", rocrate, {}, openpmd)
    assert "Matched the query" in answer
    assert "openPMD iterations" in answer
    assert "Laser sweep" not in answer


def test_synthesize_answer_no_match_reports_and_falls_back() -> None:
    answer = analysis.synthesize_answer("zzz-nonexistent", {"name": "x"}, {}, {})
    assert "Cannot answer the physics question" in answer
    assert "name is x" in answer


_HISTOGRAM = {
    "total": 44.0,
    "max_energy_kev": 17500.0,
    "count_in_window": {"min_kev": 100.0, "max_kev": 1000.0, "count": 0.0},
    "source_path": "e_energyHistogram_all.dat",
    "iteration": 100,
}


def test_plugin_facts_name_the_physics() -> None:
    facts = analysis._plugin_facts({"energy_histogram": _HISTOGRAM})
    joined = "; ".join(facts)
    assert "44" in joined
    assert "17500" in joined
    assert "e_energyHistogram_all.dat" in joined


def test_physics_query_is_answered_even_without_a_literal_match() -> None:
    """The beta-4 regression: a physics question must yield physics, not metadata."""
    answer = analysis.synthesize_answer(
        "which focal point maximizes the high-energy tail?",
        {"name": "Laser sweep"},
        {},
        {},
        {"energy_histogram": _HISTOGRAM},
    )
    assert "17500" in answer
    assert "e_energyHistogram_all.dat" in answer


def test_literal_physics_query_matches_the_plugin_fact() -> None:
    answer = analysis.synthesize_answer("max energy", {}, {}, {}, {"energy_histogram": _HISTOGRAM})
    assert "Matched the query" in answer
    assert "17500" in answer


def test_no_physics_is_stated_explicitly() -> None:
    """With no openPMD and no plugin histogram, say so instead of metadata only."""
    answer = analysis.synthesize_answer("max energy", {"name": "Laser sweep"}, {}, {}, {})
    assert "Cannot answer the physics question" in answer
    assert "no openPMD output and no plugin histogram" in answer
    assert "Laser sweep" in answer


def test_openpmd_without_plugin_is_stated_explicitly() -> None:
    answer = analysis.synthesize_answer("max energy", {}, {}, {"latest_step": 10}, {})
    assert "no plugin histogram" in answer
    assert "openPMD output is present" in answer


def test_unavailable_reader_is_named_in_the_answer() -> None:
    plugins = {"__unavailable__": {"reason": "the optional picongpu plugin readers are not installed"}}
    answer = analysis.synthesize_answer("max energy", {}, {}, {}, plugins)
    assert "picongpu plugin readers are not installed" in answer


def test_read_plugin_summaries_reuses_the_results_engine(tmp_path, monkeypatch) -> None:
    from pic_agentic import results as results_mod

    out = tmp_path / "run" / "simOutput"
    out.mkdir(parents=True)

    def fake_resolve(params, *, run_dir, sim_id):
        _ = (run_dir, sim_id)
        if params.reader == "energy_histogram":
            return {"result": dict(_HISTOGRAM)}
        return {"error": "no such file", "error_code": "no_results"}

    monkeypatch.setattr(results_mod, "resolve_result", fake_resolve)
    summaries = analysis.read_plugin_summaries(out)
    assert summaries["energy_histogram"]["max_energy_kev"] == pytest.approx(17500.0)
    assert "phase_space" not in summaries


def test_read_plugin_summaries_remembers_reader_unavailable(tmp_path, monkeypatch) -> None:
    from pic_agentic import results as results_mod

    out = tmp_path / "run" / "simOutput"
    out.mkdir(parents=True)
    monkeypatch.setattr(
        results_mod,
        "resolve_result",
        lambda _params, **_kwargs: {"error": "no picongpu", "error_code": "reader_unavailable"},
    )
    summaries = analysis.read_plugin_summaries(out)
    assert summaries["__unavailable__"]["reason"] == "no picongpu"


def test_read_plugin_summaries_without_output_is_empty(tmp_path) -> None:
    assert analysis.read_plugin_summaries(tmp_path / "missing") == {}


def test_analyze_never_raises_on_garbage(tmp_path) -> None:
    bad = tmp_path / "input"
    bad.mkdir()
    (bad / "ro-crate-metadata.json").write_text("{not json", encoding="utf-8")
    (bad / "metadata").mkdir()
    (bad / "metadata" / "rc_params.json").write_text("[1,2,3]", encoding="utf-8")
    sections = analysis.analyze(tmp_path / "run", bad, tmp_path / "missing")
    assert set(sections) == {"rocrate", "metadata", "openpmd", "plugins", "answer"}
    assert sections["rocrate"] == {}
    assert isinstance(sections["answer"], str)


def test_analyze_derives_setup_from_run_dir(tmp_path) -> None:
    setup = _setup(tmp_path)
    (setup.parent / "run").mkdir()
    sections = analysis.analyze(tmp_path / "run", None, None)
    assert sections["rocrate"]["name"]


def test_analyze_with_no_paths_is_empty_but_valid() -> None:
    sections = analysis.analyze(None, None, None)
    assert sections["rocrate"] == {}
    assert "No analysis metadata" in sections["answer"]


def test_analyze_rejects_symlinked_setup_escape(tmp_path) -> None:
    """A symlinked ``input`` must not let analysis read outside the run base."""
    base = tmp_path / "base"
    (base / "run").mkdir(parents=True)
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "ro-crate-metadata.json").write_text(
        '{"@graph": [{"@id": "./", "name": "SECRET CRATE"}]}',
        encoding="utf-8",
    )
    (base / "input").symlink_to(outside)
    sections = analysis.analyze(base / "run", None, None)
    assert sections["rocrate"] == {}


def test_readers_never_raise_on_bad_bytes(tmp_path) -> None:
    setup = tmp_path / "input"
    (setup / "metadata").mkdir(parents=True)
    (setup / "ro-crate-metadata.json").write_bytes(b"\xff\xfe not utf-8")
    (setup / "metadata" / "rc_params.json").write_bytes(b"\x00null byte")
    assert analysis.read_rocrate(setup) == {}
    assert analysis.read_pypicongpu_metadata(setup)["rc_params"] == {}
    # A null byte in the path itself must not raise either.
    assert analysis.read_rocrate("bad\x00path") == {}
